### ISSUE TITLE
bin/ok command fails

### ISSUE THREAD

**Issue by johnnypea** [Morebec/OrkestraMono#2]
MacOS 11.4

```
❯ bin/ok up
Failed to execute process 'bin/ok'. Reason:
The file 'bin/ok' specified the interpreter '/usr/bin/bash', which is not an executable command.
```

```
❯ which -a bash
/usr/local/bin/bash
/bin/bash
```

**Comment by jwillp** [comment]
@johnnypea  A quick fix would be to change the shebang to `#!/usr/bin/env bash`.

Can you run the `/usr/bin/env bash` in a terminal and confirm that it launches bash?

If it works I am going to make the changes.

**Comment by johnnypea** [comment]
Yes, that works. Thanks.
